language: python
python:
  - 3.5
  - 3.9

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install --user -r requirements.txt --use-feature=2020-resolver

script:
  - python -m unit_test.py