language: python
python:
  - 3.9
  - 3.5

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt --use-feature=2020-resolver

script:
  - python -m unit_test.py